### ISSUE TITLE
add public function setCustomFields($fields) to push all custom fields at once

### ISSUE THREAD

**Issue by yurii-zhukow** [hellosign/hellosign-php-sdk#28] opened 2016-04-29 08:52 UTC
so, user can push all custom fields as an array.
also, add support for complex custom fields as described in documentation
i.e. 
$filedName => array('value' => $value, 'editor' => $editor, 'type' => $type) etc...
so all custom fields could be configured outside the api and pushed at once.

**Comment by desmondw** [comment] 2016-05-12 22:51
This is a duplicate of another issue: https://github.com/HelloFax/hellosign-php-sdk/issues/20

**Closed as completed by desmondw** 2016-05-12 22:51 UTC

**Comment by BHSPitMonkey** [comment] 2016-05-13 00:10
@yurii-zhukow to give you a more detailed response, since your issue had two parts to it:

> add public function setCustomFields($fields) to push all custom fields at once
> 
> so, user can push all custom fields as an array.

There's not a pressing need to add something like this to the SDK. If you have an array of `$fields`, you can just loop over that array and make calls to `setCustomField` one at a time. For example:

``` php
foreach ($fields as $f) {
  $request->setCustomField($f['name'], $f['value'], ...);
}
```

> also, add support for complex custom fields as described in documentation

This is covered by #20 and being worked on.

Thanks for your feedback!
